In [75]:
import numpy as np

In [76]:
unpadded_array = arr_padded
for i in range(arr_padded.ndim):
    length = arr_padded.shape[i]
    slices = [slice(None, None,None)]*arr_padded.ndim
    slices[i] = slice(2,length-2,None)
    unpadded_array =unpadded_array[tuple(slices)]


NameError: name 'arr_padded' is not defined

In [ ]:
import numpy as np
random_arr = np.random.randn(2,2)
np.pad(random_arr, ((2,2),(2,2)))

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.29455742, -0.97127459,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.05102565, -0.98312818,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [ ]:
from Tensor import Tensor
import numpy as np

In [ ]:
a = Tensor(np.array([1,2,3]))

In [ ]:
b = Tensor(np.array([4,5,6]))

In [ ]:
a.reshape((3,1))

Tensor(data = [[1]
 [2]
 [3]], grad = 0)

In [ ]:
import inspect

def get_user_attributes(cls):
    boring = dir(type('dummy', (object,), {}))
    return [item
            for item in inspect.getmembers(cls)
            if item[0] not in boring]

In [ ]:
a.shape

(3,)

In [ ]:
a.transpose().shape

(3,)

In [ ]:
np.pad(random_arr, (2,2)).shape

(6, 6)

In [ ]:
arr.shape

(2, 2)

In [ ]:
np.pad(arr, ((3, 2), (2, 3)), 'minimum')

array([[1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1]])

In [ ]:
a = [[1, 2], [3, 4]]
np.pad(a, ((3, 2), (2, 3)), 'minimum')

array([[1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 2, 1, 1, 1]])

In [ ]:
unpadded_array

array([[4, 6, 4],
       [8, 5, 3]])

In [ ]:
def im2col(input_data, filter_h, filter_w, stride=1, pad=0):
    r"""Transform 4 dimensional images to 2 dimensional array.
    From stanford university cs231n assignment 2.
    More [here](http://cs231n.stanford.edu/).

    Args:
        input_data (Tensor): 4 dimensional input images (The number of images, The number of channels, Height, Widht)
        filter_h (int): height of filter
        filter_w (int): width of fitter
        stride (int): the interval of stride
        pad (int): the interval of padding

    Returns:
        col (Tensor): 2 dimnesional tensor

    .. warning::

        This function is not compatible with ``autograd``system. The resulting ``Tensor`` has no links to a
        previous computational graph, and in addition its gradient is set to ``None``.

    """
    # Extract the shape from one's image
    N, C, H, W = input_data.shape

    # Make sure that the convolution can be executed
    # TODO: replace by a warning
    assert (H + 2 * pad - filter_h) % stride == 0, f'invalid parameters, (H + 2 * pad - filter_h) % stride != 0, got ' \
                                                   f'H={H}, pad={pad}, filter_h={filter_h}, stride={stride}'
    assert (W + 2 * pad - filter_w) % stride == 0, f'invalid parameters, (W + 2 * pad - filter_w) % stride != 0, got ' \
                                                   f'W={W}, pad={pad}, filter_w={filter_w}, stride={stride}'
    # Initialize the output dimensions
    out_h = (H + 2 * pad - filter_h) // stride + 1
    out_w = (W + 2 * pad - filter_w) // stride + 1
    # Pad the input data
    padding = ((0, 0), (0, 0), (pad, pad), (pad, pad))
    image = nets.pad(input_data, padding)
    # Initialize the output
    col = nets.zeros((N, C, filter_h, filter_w, out_h, out_w))

    # For loops...
    for y in range(filter_h):
        y_max = y + stride * out_h
        for x in range(filter_w):
            x_max = x + stride * out_w
            col[:, :, y, x, :, :] = image[:, :, y:y_max:stride, x:x_max:stride]

    col = col.transpose(0, 4, 5, 1, 2, 3).reshape(N * out_h * out_w, -1)
    return col

In [ ]:
img = np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]],[[3,4,5],[6,7,8]]])

In [ ]:
import numpy as np
N = 2 # 2 images
C = 3
H = 4
W = 4
filter_h = 2
filter_w = 2
stride = 1
image = np.random.randn(N,C,H,W)
print(image)

[[[[ 6.58989223e-01 -2.60027883e-01  1.23237399e+00  1.23346458e+00]
   [-2.52429466e-01 -1.10845956e+00  1.84329960e+00 -1.65008438e+00]
   [-1.37388900e+00 -3.93228742e-02  1.49524951e-01  5.54141876e-01]
   [ 1.57419656e+00 -7.04228633e-01 -2.67698344e-02 -5.52936092e-02]]

  [[ 9.61757196e-01  6.54402912e-01  1.20023782e-01 -6.86277409e-01]
   [-3.06907256e-01  2.37223259e-01  6.91925977e-01 -1.63771426e+00]
   [-1.56311000e+00 -2.21949531e-01 -2.05308977e-01  1.17524740e+00]
   [-1.26745183e-01 -5.11528587e-01  2.16780390e-01 -2.19178336e-01]]

  [[ 1.30081129e+00  2.12125247e-01 -1.36801144e+00  9.77561881e-01]
   [-5.98144146e-02  8.28596780e-01  5.38645926e-01  1.38645951e-01]
   [-5.82173268e-01  1.45732433e-01  8.76600465e-01 -9.09821224e-01]
   [-1.16022845e-01  1.39945545e+00 -7.51955452e-01 -1.72473698e-01]]]


 [[[-4.71853569e-01 -1.05629618e+00  3.17709774e-01 -3.78260448e-01]
   [ 1.77857612e+00 -2.48681075e-01  2.00759241e+00  1.85364706e-03]
   [ 6.30990277e-01  1.598

In [ ]:
out_h = (H  - filter_h) // stride + 1
out_w = (W  - filter_w) // stride + 1

In [ ]:
out_h

3

In [ ]:
test_case = np.randn((N, C, H, W))

(18, 12)

In [ ]:
# why not 
col2 = np.zeros((N,C, filter_h, filter_w, out_h, out_w))

for i in range(out_h):
    for j in range(out_w):
        # populating each kernel, each SLIDE, 1 slide along each direction
        # (filter_h x filter_w) corresponds to the num of entries, size of the kernel

        # get all the elements:
        image[col2:]

In [ ]:
col = np.zeros((N,C, filter_h, filter_w, out_h, out_w)) # Num entries per convolution (N x C x filter_w x filter H) , num convolutions per Convolution (out_h x out_w). 

    # For loops...
for y in range(filter_h):
        # for each element of filter_h, we are extracting all the elements it has touched.
        y_max = y + stride * out_h
        #print(y_max)
        for x in range(filter_w):
            x_max = x + stride * out_w
            # For each element of the kernel, we are extracting all the entries that it has touched.
            # Extracts the elements of size out_h x out_w for each filter_h x filter_w combo
            print(f'{y_max=},{x_max = }, {image[:, :, y:y_max:stride, x:x_max:stride]}')
            col[:, :, y, x, :, :] = image[:, :, y:y_max:stride, x:x_max:stride]

col = col.transpose(0, 4, 5, 1, 2, 3).reshape(N * out_h * out_w, -1)
print(col)

y_max=3,x_max = 3, [[[[ 0.65898922 -0.26002788  1.23237399]
   [-0.25242947 -1.10845956  1.8432996 ]
   [-1.373889   -0.03932287  0.14952495]]

  [[ 0.9617572   0.65440291  0.12002378]
   [-0.30690726  0.23722326  0.69192598]
   [-1.56311    -0.22194953 -0.20530898]]

  [[ 1.30081129  0.21212525 -1.36801144]
   [-0.05981441  0.82859678  0.53864593]
   [-0.58217327  0.14573243  0.87660047]]]


 [[[-0.47185357 -1.05629618  0.31770977]
   [ 1.77857612 -0.24868108  2.00759241]
   [ 0.63099028  1.59858283 -1.13712626]]

  [[ 0.8763872   0.26392184  0.21677024]
   [-1.09560144  0.59341059  1.47906806]
   [ 0.67538955 -0.53174213 -0.5668139 ]]

  [[-1.876026   -0.68364663  0.92193507]
   [-1.81510213 -0.91307233  0.30885282]
   [-0.26929717 -0.95215643 -0.41441323]]]]
y_max=3,x_max = 4, [[[[-2.60027883e-01  1.23237399e+00  1.23346458e+00]
   [-1.10845956e+00  1.84329960e+00 -1.65008438e+00]
   [-3.93228742e-02  1.49524951e-01  5.54141876e-01]]

  [[ 6.54402912e-01  1.20023782e-01 -6.86277409e

In [ ]:
out_h = (4 + 2 * pad - 2) // stride + 1
out_w = (W + 2 * pad - filter_w) // stride + 1

In [ ]:
    for y in range(filter_h):
        y_max = y + stride * out_h
        for x in range(filter_w):
            x_max = x + stride * out_w
            col[:, :, y, x, :, :] = image[:, :, y:y_max:stride, x:x_max:stride]

In [ ]:
W = 4
stride = 2
filter_w = 2
pad = 0
out_w = (W + 2 * pad - filter_w) // stride + 1
print(out_w)

2


In [ ]:
import matplotlib as plt



ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
from utils import Im2Col, Col2Im

In [ ]:
N,C,H,W = 2,3,4,4
img = Tensor(np.random.randn(N,C,H,W))

In [ ]:
import utils

In [ ]:
output = Im2Col(img,2,2)

TypeError: 'Tensor' object does not support item assignment

In [ ]:
print(t.pad(0))

Tensor(data = [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], grad = 0)


In [ ]:
t = Tensor(np.zeros(((2,3,4))))
print(t)

Tensor(data = [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], grad = 0)


In [ ]:
import numpy as np
from tensor import Tensor

def Im2Col(input_image, kernel_h, kernel_w, stride=1, pad=0):
    '''
    input_image: Tensor of shape [BS x C x H x W]
    '''
    N,C,H,W = input_image.shape

    assert (H + 2*pad - kernel_h) % stride == 0
    assert (W + 2*pad - kernel_w) % stride == 0

    out_h = (H + 2*pad - kernel_h)//stride + 1
    out_w = (H + 2*pad - kernel_w)//stride + 1

    # pad should be a tuple specifying how much you want to pad height and width
    padded_data = input_image.pad(pad)

    col = Tensor(np.zeros((N,C, kernel_h, kernel_w, out_h, out_w)))

    for y in range(kernel_h):
        y_max = y + stride*out_h # y_max is the max idx the kernel sees.

        for x in range(kernel_w):
            x_max = x + stride*out_w

            # We extract the num of entries each part of the kernel touches
            # Each extraction will be of shape [N x C x out_h x out_w] because out_h x out_W is the num of convs performed.
            col[:,:,y,x] = padded_data[:,:,y:y_max:stride, x:x_max:stride]

    return col.transpose(0,4,5,1,2,3).reshape(N*out_h*out_w, -1) 
    # We want [N*out_h*out_w, num entries ] -> the output images for each image in batch x filter size * C (num of entries)


def Col2Im(col, img_shape, kernel_h, kernel_w, stride = 1, pad = 0):

    N, C, H, W = img_shape

    out_h = (H + 2 * pad - kernel_h) // stride + 1
    out_w = (W + 2 * pad - kernel_w) // stride + 1

    col= col.reshape(N,out_h, out_w, C, kernel_h, kernel_w).transpose(0,3,4,5,1,2)

    image = np.zeros((N,C,H + 2 * pad + stride - 1, W + 2 * pad + stride - 1)) # ???
    # we want to get the padded matrix, 

    for y in range(kernel_h):
        y_max = y + stride * out_h
        for x in range(kernel_w):
            x_max = x + stride * out_w
            image[:, :, y:y_max:stride, x:x_max:stride] += col[:, :, y, x, :, :]
    
    print('image after', image.shape)
    return image[:, :, pad:H + pad, pad:W + pad]

In [ ]:
output_size = lambda x: x+

In [ ]:
K = 5
C = 3
FH, FW = 2,2
H,W = 4,4
N = 2

out_h = H - FH + 1
out_w = W - FW + 1

dout = np.random.randn(N, K, out_h, out_w)
x_col = np.random.randn(N*out_h*out_w, C*FH*FW) # [num convs , patch]
dout_t = dout.transpose(0,2,3,1).reshape(-1,K) # [num_convs, K]

dw_col = x_col.T @ dout_t# [num_convs, patch].T x [num_convs x K] -> [patch x K]
dw_col = dw_col.transpose(1,0).reshape(K, C, FH, FW) # dw -> K,C, FH, FW

dout_t2 = dout.transpose(0,2,3,1).reshape(K,-1)
dw = dout_t2 @ x_col # [K, num_convs] x [num_convs x patch]
dw = dw.reshape(K, C, FH, FW)

In [ ]:
dw

array([[[[ -3.49113263,  -0.02521229],
         [ -2.75414599,  -4.9803317 ]],

        [[  5.05131694,   2.95751468],
         [  2.85769525,  -5.43319955]],

        [[ -4.60997143,   4.10372013],
         [  3.50876173,  -6.79019394]]],


       [[[  3.12234928,   2.40180591],
         [  2.40275619,   1.33252241]],

        [[  3.57804806,  -1.78218324],
         [ -0.10269539,  -5.09705624]],

        [[  0.60290801,  -1.61190165],
         [ -2.86592964,  -4.43652769]]],


       [[[ -1.07950074,   0.42269824],
         [ -4.28748527,  -3.55926836]],

        [[  2.44073626,  -4.14538545],
         [ -1.93794666,  -0.07649018]],

        [[  5.64914391,  -1.93692556],
         [ -0.12822287,   2.28227619]]],


       [[[ -0.63614634,   1.59308568],
         [  3.057244  ,  -1.73683581]],

        [[-12.95588836,   2.1228131 ],
         [ -8.22367565,  13.05672009]],

        [[ -6.48097848,   1.79922165],
         [  0.1304148 ,   3.53623333]]],


       [[[ -1.09407536,   4.5494

In [ ]:
import numpy as np
from tensor import Tensor

def Im2Col(input_image, kernel_h, kernel_w, stride=1, pad=0):
    '''
    input_image: Tensor of shape [BS x C x H x W]
    '''
    N,C,H,W = input_image.shape

    assert (H + 2*pad - kernel_h) % stride == 0
    assert (W + 2*pad - kernel_w) % stride == 0

    out_h = (H + 2*pad - kernel_h)//stride + 1
    out_w = (H + 2*pad - kernel_w)//stride + 1

    # pad should be a tuple specifying how much you want to pad height and width
    padded_data = input_image.pad(pad)

    col = Tensor(np.zeros((N,C, kernel_h, kernel_w, out_h, out_w)))
    print('wut')
    print(col.shape)

    for y in range(kernel_h):
        y_max = y + stride*out_h # y_max is the max idx the kernel sees. 
        # Why? because stride is the amount we move the slide the kernel for each convolution & out_h is the num of convs we perform along y.

        for x in range(kernel_w):
            x_max = x + stride*out_w

            # We extract the num of entries each part of the kernel touches.
            # E.g a 2x2 kernel -> what entries of the image does k_1,1 see?
            # Each extraction will be of shape [N x C x out_h x out_w] because out_h x out_W is the num of convs performed.
            #print(col[:,:,y,x,:,:].shape)
            #print(padded_data[:,:,y:y_max:stride, x:x_max:stride].shape)
            col[:,:,y,x,:,:] = padded_data[:,:,y:y_max:stride, x:x_max:stride]
    print(col.shape)
    return col.transpose((0,4,5,1,2,3)).reshape((N*out_h*out_w, -1))  # convs x patches
    # We want [N*out_h*out_w, num entries ] -> the output images for each image in batch x filter size * C (num of entries)


def Col2Im(col, img_shape, kernel_h, kernel_w, stride = 1, pad = 0):

    N, C, H, W = img_shape

    out_h = (H + 2 * pad - kernel_h) // stride + 1
    out_w = (W + 2 * pad - kernel_w) // stride + 1

    col= col.reshape((N,out_h, out_w, C, kernel_h, kernel_w)).transpose((0,3,4,5,1,2))

    image = Tensor(np.zeros((N,C,H + 2 * pad + stride - 1, W + 2 * pad + stride - 1))) # ???
    print(f'{image.shape=}')
    # we want to get the padded matrix, but why + stride?

    # Essentially takes and disperses. 
    for y in range(kernel_h):
        y_max = y + stride * out_h
        for x in range(kernel_w):
            x_max = x + stride * out_w
            # += because of total derivative. 
            # y:y_max:stride are the indices (of the img) seen by the kernel idx (y,x) as it slides along.
            # the indices tell us which indices (entries of X) w has seen. 
            # image[:, :, y:y_max:stride, x:x_max:stride] -> the specific x val, dL/dx_i,j
            image[:, :, y:y_max:stride, x:x_max:stride] = col[:, :, y, x] + image[:, :, y:y_max:stride, x:x_max:stride]

    print('image after', image.shape)

    return image[:, :, pad:H + pad, pad:W + pad]

In [ ]:
t = Tensor(np.zeros((3,4,5)))

In [ ]:
img3 = col2im(col.data, (N,C,H,W), 2,2, padding = 0)

In [ ]:
print(img)
print(img3)

Tensor(data = [[[[-0.60302473 -0.15342031  1.3303752  -1.02497474]
   [ 0.01827547 -0.06711329  0.25193848 -0.75097839]
   [ 1.32224517 -1.51295631  1.07776847  1.72961163]
   [-0.58448618  1.82300701  0.12378387  1.18943251]]]], grad = 0)
[[[[-6.03024730e-01 -1.17839505e+00  2.70213956e-01 -7.50978389e-01]
   [-1.58006959e+00  2.76563064e+00  2.24408655e-03  2.40001364e+00]
   [-8.18091676e-01  1.63975766e+00  3.11665741e+00  1.32970695e+00]
   [ 1.32224517e+00  2.16655321e-01 -4.60702310e-01  1.18943251e+00]]]]


In [ ]:

col = Im2Col(img, 2,2)
print(img)
print(col)

img2 = Col2Im(col, (N,C,H,W), 2,2)
print(img2)

wut
(1, 1, 2, 2, 3, 3)
(1, 1, 3, 3)
(1, 1, 3, 3)
(1, 1, 3, 3)
(1, 1, 3, 3)
(1, 1, 3, 3)
(1, 1, 3, 3)
(1, 1, 3, 3)
(1, 1, 3, 3)
(1, 1, 2, 2, 3, 3)
Tensor(data = [[[[-0.79608946  1.02926435 -2.0582537   0.26175885]
   [ 1.684163   -0.93418648 -1.03344877 -1.20104663]
   [ 0.73651828 -0.57770761 -1.78893679  0.49821182]
   [ 0.32410088 -1.6996683   1.77529668 -2.41897758]]]], grad = 0)
Tensor(data = [[-0.79608946  1.02926435  1.684163   -0.93418648]
 [ 1.02926435 -2.0582537  -0.93418648 -1.03344877]
 [-2.0582537   0.26175885 -1.03344877 -1.20104663]
 [ 1.684163   -0.93418648  0.73651828 -0.57770761]
 [-0.93418648 -1.03344877 -0.57770761 -1.78893679]
 [-1.03344877 -1.20104663 -1.78893679  0.49821182]
 [ 0.73651828 -0.57770761  0.32410088 -1.6996683 ]
 [-0.57770761 -1.78893679 -1.6996683   1.77529668]
 [-1.78893679  0.49821182  1.77529668 -2.41897758]], grad = 0)
Tensor(data = [[[[-0.79608946  2.05852869 -4.11650741  0.26175885]
   [ 3.36832599 -3.73674592 -4.13379508 -2.40209326]
   [ 1.47

In [ ]:
col.shape

(9, 4)

In [ ]:
1.01954974*2

2.03909948

In [ ]:
import numpy as np
from module import Module
from tensor import Tensor
#from utils import Im2Col, Col2Im


class Convolution2D(Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, pad=0):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.pad= pad

        self.kernel_weights = Tensor(np.random.randn(out_channels,in_channels, *kernel_size))
        self.kernel_bias = Tensor(np.zeros(out_channels)) # we add a bias for each channel

    def forward(self, x):
        self._cache['x'] = x
        out_channels, in_channels, kernel_h, kernel_w = self.kernel_weights.shape
        # W_out = (W_in - K + 2P)/S + 1 
        N, C, H, W = x.shape
        H_out = int((H - kernel_h + 2*self.pad)/ self.stride + 1)
        W_out = int((W - kernel_w + 2*self.pad)/ self.stride + 1)
        print(f'{H_out=}, {W_out=}')

        col_weights = self.kernel_weights.reshape((out_channels , -1)).transpose() #[patch,K]
        col = Im2Col(x, kernel_h, kernel_w, self.stride, self.pad) # [convs x patch]
        print(f'{col_weights.shape=}, {col.shape=}')

        output = col @ col_weights + self.kernel_bias # convs x K
        output =  output.reshape((N, H_out, W_out, -1)).transpose((0, 3, 1, 2))

        self._cache['x_col'] = col
        self._cache['col_weights'] = col_weights

        return output

    def backward(self, dout):
        # output shape -> N,K, Hout, Wout
        dout = dout.transpose((0,2,3,1)).reshape((-1, self.out_channels)) # [N, Hout, Wout, K] -> [N*Hout*Wout, K] -> [convs, K]
        db = dout.sum_(axis = 0) # we sum along the N*Hout*Wout axis -> (K,)
        print(f"{dout.shape=}, {self._cache['x_col'].shape=}")
        dw_col = self._cache['x_col'].transpose() @ dout # [patch x convs] x [convs x K]-> [patch x K], dout is the filter!
        print(f'{dw_col.shape=}')
        dw = dw_col.transpose((1,0)).reshape((self.out_channels, self.in_channels, *self.kernel_size))

        # Downstream gradient, dx = a full convolution of 180 deg rotated filter with dout.
        print(f"{dout.shape=}, {self._cache['col_weights'].shape=}, {self._cache['col_weights'].transpose().shape=}")
        dx_col = dout @ self._cache['col_weights'].transpose() # [convs, K] x [K, patch] -> [convs x patch]
        dx = Col2Im(dx_col, self._cache['x'].shape, *self.kernel_size, self.stride, self.pad)

        self._cache['weights'] = dw
        self._cache['bias'] = db

        return dx

    def __call__(self,x):
        return self.forward(x)

In [ ]:
import torch.nn as nn
class MyBatchNorm2d(nn.BatchNorm2d):
    def __init__(self, num_features, eps=1e-5, momentum=0.1,
                 affine=True, track_running_stats=True):
        super(MyBatchNorm2d, self).__init__(
            num_features, eps, momentum, affine, track_running_stats)

    def forward(self, input):
        self._check_input_dim(input)

        exponential_average_factor = 0.0

        if self.training and self.track_running_stats:
            if self.num_batches_tracked is not None:
                self.num_batches_tracked += 1
                if self.momentum is None:  # use cumulative moving average
                    exponential_average_factor = 1.0 / float(self.num_batches_tracked)
                else:  # use exponential moving average
                    exponential_average_factor = self.momentum

        # calculate running estimates
        if self.training:
            mean = input.mean([0, 2, 3])
            print(mean)
            # use biased var in train
            var = input.var([0, 2, 3], unbiased=False)
            n = input.numel() / input.size(1)
            print(exponential_average_factor)
            with torch.no_grad():
                self.running_mean = exponential_average_factor * mean+ (1 - exponential_average_factor) * self.running_mean
                # update running_var with unbiased var
                self.running_var = exponential_average_factor * var * n / (n - 1)+ (1 - exponential_average_factor) * self.running_var
        else:
            mean = self.running_mean
            var = self.running_var

        print(var)
        print(torch.sqrt(var[None, :, None, None] + self.eps))
        input = (input - mean[None, :, None, None]) / (torch.sqrt(var[None, :, None, None] + self.eps))
        print(input)
        if self.affine:
            input = input * self.weight[None, :, None, None] + self.bias[None, :, None, None]

        return input

In [ ]:
bn2 = MyBatchNorm2d(3)
o2 = bn2(torch_img)

tensor([-0.0333,  0.2346,  0.1881])
0.1
tensor([1.1515, 1.0253, 0.8117])
tensor([[[[1.0731]],

         [[1.0126]],

         [[0.9009]]]])
tensor([[[[-0.9140,  1.5541, -0.4857,  2.6703],
          [-2.2852,  1.3853, -0.3243, -0.2378],
          [-0.2192, -0.7823,  0.6649,  1.4055],
          [-0.9424,  0.1205,  1.0601,  0.1943]],

         [[-2.1895,  1.3304,  0.2900,  1.7394],
          [-1.4406,  1.4581,  0.2652,  1.5393],
          [ 0.8078,  0.7346,  0.0826, -0.7826],
          [ 0.5718, -0.0468, -0.2557, -0.6868]],

         [[-1.3961,  0.9195,  0.5097,  0.0304],
          [ 0.4641,  0.3996, -0.2782, -0.4890],
          [ 0.3179, -2.0279, -0.0979,  1.3985],
          [-0.9711, -0.2634,  0.6741, -0.4993]]],


        [[[ 0.5729,  0.2872,  1.1061,  0.2904],
          [ 1.0168, -0.1672, -0.8937,  0.3250],
          [-1.0344, -0.4336, -0.7510, -1.4438],
          [-0.8650,  0.1839, -0.5817, -0.4762]],

         [[-0.2066,  1.9514, -1.1443, -0.3223],
          [ 0.0250,  0.4032, -0.30

In [ ]:
img_data = img.data
print(img.shape)

(2, 3, 4, 4)


In [ ]:
torch_img[:,0,:,:].mean()

tensor(-0.0333)

In [ ]:
mean=0
for i in range(2):
    for j in range(4):
        for k in range(4):
            mean+=torch_img[i,0,j,k].item()

mean /= 32

print(mean)

-0.033336872700601816


In [ ]:
torch.mean(torch_img, axis=[0,2,3])

tensor([-0.0333,  0.2346,  0.1881])

In [ ]:
bn2.weight

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)

In [ ]:
conv_layer = Convolution2D(in_channels=1, out_channels=1, stride=2, kernel_size = (2,2))
cov_output = conv_layer(img)
dout = Tensor(np.ones_like(cov_output.data))
dx=conv_layer.backward(dout)

H_out=2, W_out=2
wut
(1, 1, 2, 2, 2, 2)
(1, 1, 2, 2, 2, 2)
col_weights.shape=(4, 1), col.shape=(4, 4)
dout.shape=(4, 1), self._cache['x_col'].shape=(4, 4)
dw_col.shape=(4, 1)
dout.shape=(4, 1), self._cache['col_weights'].shape=(4, 1), self._cache['col_weights'].transpose().shape=(1, 4)
image.shape=(1, 1, 5, 5)
image after (1, 1, 5, 5)


In [ ]:
dx.shape

(1, 1, 4, 4)

In [ ]:
from module import Module

class BatchNorm(Module):
    def __init__(self, num_feats):
        super().__init__()
        self.eps = 1e-10
        self.gamma = Tensor(np.ones(num_feats))
        self.beta = Tensor(np.zeros(num_feats))

    def forward(self,x):
        print('Changed', self.gamma, self.beta)
        BS, C, H, W = x.shape
        self._cache['x'] = x
        mu = x.mean(axis = (0,2,3),keepdims=True) # find mean across batch
        print(f'{mu=}')
        var = Tensor(np.var(x.data, axis=(0,2,3), keepdims=True))
        print(f'{var=}')
        x_hat = (x-mu)/(var + self.eps)**0.5

        self._cache['mu'] = mu
        self._cache['var'] = var
        self._cache['x_hat'] = x_hat

        return self.gamma[None,:,None,None] * x_hat + self.beta[None,:,None,None]

    def backward(self, dout):
        x = self._cache['x']
        BS = x.shape[0]
        x_hat = self._cache['x_hat']
        mu = self._cache['mu']
        var = self._cache['var']

        dBeta = dout.sum(axis=0)
        dGamma = (dout * x).sum(axis = 0) # gets rid of row dim.
        
        dx_hat = Tensor(np.ones_like(x_hat)*self.gamma)

        # dvar has shape [1 x F], a row vector. We broadcast it to add rows.
        #we also need to broadcast gamma.
        # but then we also need to sum over batch dim.
        dVar = -0.5*self.gamma*(x - mu)*(var+ self.eps)**-1.5
        dMu =  (dx_hat*-1*(var + self.eps)**-0.5).sum(axis=0) + dVar * (-2*(x - mu).sum(0))/ (BS+1) # 2nd part -> same batch get same mu, so we sum over it.
        
        # Downstream gradient
        dx = dx_hat*(var-self.eps)**-0.5 +  dVar*2*(x - mu)*1/(BS+1) + dMu * Tensor(np.ones_like(x)*1/BS)
        # nicer -> we don't have to worry abouit broadcasting since its wrt to x_hat (which is not broadcatsed along batch dim as mu/var is)

        return dx

In [ ]:
import torch.nn as nn
# With square kernels and equal stride
m = nn.Conv2d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50, 100)
output = m(input)

In [ ]:
l = nn.Linear(10,5)
ins = torch.randn(2,10)
o = l(ins)
print(o)

tensor([[-0.1399, -0.2331, -1.0112, -1.7236, -0.9243],
        [ 1.2114, -1.0815,  0.5321,  0.0063,  0.3058]],
       grad_fn=<AddmmBackward0>)


In [ ]:
from tensor import Tensor
import numpy as np
BS, C = 5,6 # C= classes
logits = Tensor(np.random.randn(BS,C))


In [ ]:
from losses import CrossEntropyLossWithLogits

In [ ]:
targets = Tensor(np.random.randint(1,7, size=5))
print(targets)

Tensor(data = [1 2 3 1 3], grad = 0)


In [ ]:
targets.data.flatten().shape

(5,)

In [ ]:
from module import Module
class CrossEntropyLossWithLogits(Module):
    def __init__(self):
        super().__init__()

    def forward(self, logits, targets):
         # logits: shape -> [BS x C]
         # targets: shape of [BS x 1] containing the index of the correct class.
        
        BS = logits.shape[0]
        print(BS)
        probs = logits.exp()/logits.exp().sum(axis=1, keepdims=True)
        print(probs)

        log_probs = probs.log()
        out= log_probs[np.arange(BS),targets.data].mean(None, False)
        self._cache['probs'] = probs
        self._cache['targets'] = targets
        return Tensor(-out.data, children=(logits,), backward_ = self.backward)
    
    def backward(self):
        targets = self._cache['targets']
        probs = self._cache['probs'].data.copy()
        BS = probs.shape[0]
        probs[np.arange(BS),targets.data] -= 1

        logits.grad = probs * 1/BS
    

In [ ]:
targets

Tensor(data = [3 4 2 5 1], grad = 0)

In [ ]:
ce._cache['probs']

Tensor(data = [[0.01618824 0.0181527  0.01873393 0.1679585  0.74541591 0.03355071]
 [0.11775372 0.38053407 0.06203892 0.05964667 0.1671127  0.21291392]
 [0.12206319 0.19953055 0.02061003 0.15993249 0.10279152 0.39507222]
 [0.07391515 0.09794317 0.10051482 0.15569171 0.55682644 0.01510871]
 [0.18563457 0.21681835 0.20503632 0.18754805 0.17118234 0.03378037]], grad = 0)

In [ ]:
logits

Tensor(data = [[ 0.98962585 -1.21086516  0.9201605  -0.6060701   0.53535812 -0.8642163 ]
 [-1.41222666 -1.70222414 -0.72416473 -0.06802758 -0.61769996 -0.4327944 ]
 [ 0.62321913  1.3630514   0.05176756 -0.58478947 -0.12717756  1.01762086]
 [-1.11147511  0.92940638  0.19036226  0.92176364 -1.52820926  1.01642512]
 [-0.25773608  1.23570485  0.25171192  1.12128547  0.06688595 -0.36256591]], grad = 0)

In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
loss_true.backward()

In [77]:
logits

Tensor(data = [[-0.83146265 -0.71692878 -0.68541147  1.50796891  2.99819433 -0.10268995]
 [-0.66576502  0.50721538 -1.30659834 -1.34592209 -0.31569194 -0.07347239]
 [ 0.51279461  1.00422308 -1.26596655  0.7830075   0.34095856  1.68732432]
 [ 0.45066923  0.73213894  0.75805665  1.19562934  2.47000506 -1.13697702]
 [-0.39698921 -0.24170935 -0.29758213 -0.38673419 -0.47803996 -2.10088937]], grad = [[ 0.00323765 -0.19636946  0.00374679  0.0335917   0.14908318  0.00671014]
 [ 0.02355074  0.07610681 -0.18759222  0.01192933  0.03342254  0.04258278]
 [ 0.02441264  0.03990611  0.00412201 -0.1680135   0.0205583   0.07901444]
 [ 0.01478303 -0.18041137  0.02010296  0.03113834  0.11136529  0.00302174]
 [ 0.03712691  0.04336367  0.04100726 -0.16249039  0.03423647  0.00675607]])

In [ ]:
logs.grad

tensor([[ 0.0032, -0.1964,  0.0037,  0.0336,  0.1491,  0.0067],
        [ 0.0236,  0.0761, -0.1876,  0.0119,  0.0334,  0.0426],
        [ 0.0244,  0.0399,  0.0041, -0.1680,  0.0206,  0.0790],
        [ 0.0148, -0.1804,  0.0201,  0.0311,  0.1114,  0.0030],
        [ 0.0371,  0.0434,  0.0410, -0.1625,  0.0342,  0.0068]],
       dtype=torch.float64)

In [ ]:
logs = torch.tensor(logits.data, requires_grad=True)
loss_true = F.cross_entropy(logs, torch.tensor(targets.data, dtype=torch.long))
print(loss,loss_true)

Tensor(data = 2.5238041700119673, grad = [1]) tensor(2.5238, dtype=torch.float64, grad_fn=<NllLossBackward0>)


In [83]:
def relu(t):
    out = Tensor(np.maximum(0,t.data), (t,))

    def backward_():
      t.grad += np.where(out.data > 0, out.grad, 0)

    out.backward_ = backward_
    return out

In [90]:
o.grad = np.random.randn(o.shape[0],o.shape[1])
o.backward_()

In [92]:
print(o)
print('#####')
print(o.grad)

Tensor(data = [[0.         0.         0.         1.50796891 2.99819433 0.        ]
 [0.         0.50721538 0.         0.         0.         0.        ]
 [0.51279461 1.00422308 0.         0.7830075  0.34095856 1.68732432]
 [0.45066923 0.73213894 0.75805665 1.19562934 2.47000506 0.        ]
 [0.         0.         0.         0.         0.         0.        ]], grad = [[ 0.72236296 -0.63599729  1.04386782  0.48152774  0.57671519  0.49256578]
 [ 1.43123425  1.27770231  1.70889293 -0.52610961  0.05534279  1.17961273]
 [-1.32086715 -0.20955157  0.37325724 -1.51351102 -0.26797279  0.98404636]
 [-1.5531078   0.20738756  1.2686006   0.39666374  0.02674206 -1.03707938]
 [ 0.46347617 -0.7835005  -0.00950433  1.42494579  0.8167799  -0.33734168]])
#####
[[ 0.72236296 -0.63599729  1.04386782  0.48152774  0.57671519  0.49256578]
 [ 1.43123425  1.27770231  1.70889293 -0.52610961  0.05534279  1.17961273]
 [-1.32086715 -0.20955157  0.37325724 -1.51351102 -0.26797279  0.98404636]
 [-1.5531078   0.2073875

In [93]:
logits.grad

array([[ 0.00323765, -0.19636946,  0.00374679,  0.51511944,  0.72579837,
         0.00671014],
       [ 0.02355074,  1.35380912, -0.18759222,  0.01192933,  0.03342254,
         0.04258278],
       [-1.29645452, -0.16964546,  0.00412201, -1.68152452, -0.24741448,
         1.0630608 ],
       [-1.53832477,  0.0269762 ,  1.28870357,  0.42780208,  0.13810735,
         0.00302174],
       [ 0.03712691,  0.04336367,  0.04100726, -0.16249039,  0.03423647,
         0.00675607]])

In [85]:
o=relu(logits)

In [ ]:
ce = CrossEntropyLossWithLogits()

loss = ce(logits, targets)

5
Tensor(data = [[0.01618824 0.0181527  0.01873393 0.1679585  0.74541591 0.03355071]
 [0.11775372 0.38053407 0.06203892 0.05964667 0.1671127  0.21291392]
 [0.12206319 0.19953055 0.02061003 0.15993249 0.10279152 0.39507222]
 [0.07391515 0.09794317 0.10051482 0.15569171 0.55682644 0.01510871]
 [0.18563457 0.21681835 0.20503632 0.18754805 0.17118234 0.03378037]], grad = 0)


In [ ]:
targets_tensor = torch.tensor(targets.data, dtype=torch.long)

In [ ]:
p=torch.tensor(logits.data).softmax(dim=1)

In [74]:
loss.backward()
logits

Tensor(data = [[-0.83146265 -0.71692878 -0.68541147  1.50796891  2.99819433 -0.10268995]
 [-0.66576502  0.50721538 -1.30659834 -1.34592209 -0.31569194 -0.07347239]
 [ 0.51279461  1.00422308 -1.26596655  0.7830075   0.34095856  1.68732432]
 [ 0.45066923  0.73213894  0.75805665  1.19562934  2.47000506 -1.13697702]
 [-0.39698921 -0.24170935 -0.29758213 -0.38673419 -0.47803996 -2.10088937]], grad = [[ 0.00323765 -0.19636946  0.00374679  0.0335917   0.14908318  0.00671014]
 [ 0.02355074  0.07610681 -0.18759222  0.01192933  0.03342254  0.04258278]
 [ 0.02441264  0.03990611  0.00412201 -0.1680135   0.0205583   0.07901444]
 [ 0.01478303 -0.18041137  0.02010296  0.03113834  0.11136529  0.00302174]
 [ 0.03712691  0.04336367  0.04100726 -0.16249039  0.03423647  0.00675607]])

In [37]:
loss.backward()

In [21]:
targets_tensor

tensor([1, 2, 3, 1, 3])

In [29]:
torch.arange(BS)

tensor([0, 1, 2, 3, 4])

In [52]:
p #[torch.arange(BS),targets_tensor]

tensor([[0.0162, 0.0182, 0.0187, 0.1680, 0.7454, 0.0336],
        [0.1178, 0.3805, 0.0620, 0.0596, 0.1671, 0.2129],
        [0.1221, 0.1995, 0.0206, 0.1599, 0.1028, 0.3951],
        [0.0739, 0.0979, 0.1005, 0.1557, 0.5568, 0.0151],
        [0.1856, 0.2168, 0.2050, 0.1875, 0.1712, 0.0338]], dtype=torch.float64)

In [13]:
loss

Tensor(data = 2.213570171811923, grad = 0)

In [6]:
output

tensor([[[[ 6.5131e-01, -4.6349e-01,  1.4009e+00,  ..., -4.5093e-01,
           -8.8887e-01, -7.5581e-01],
          [ 1.4307e-01, -2.7941e-01, -7.2097e-01,  ...,  8.4199e-01,
           -3.1837e-01,  4.5393e-02],
          [-3.8615e-01, -5.9359e-01, -6.2305e-02,  ..., -1.3753e+00,
            4.9063e-01, -1.7188e-01],
          ...,
          [ 8.5481e-01,  1.7378e-01,  8.4781e-01,  ..., -5.6031e-01,
            8.9470e-01,  5.7031e-01],
          [-2.3531e-01, -1.3991e-01,  4.5517e-01,  ...,  7.5654e-03,
            3.9916e-01,  1.6169e-02],
          [ 7.9266e-01, -2.3006e-01, -1.6159e+00,  ..., -7.0827e-02,
           -1.9055e-01,  6.7308e-01]],

         [[-4.8235e-01,  3.1409e-01, -3.3970e-01,  ...,  8.2075e-01,
           -1.1019e+00, -2.0103e-01],
          [-1.3823e-01,  3.7822e-01, -1.0408e+00,  ...,  5.5848e-01,
           -1.4116e-01, -6.4103e-01],
          [ 1.0599e-01,  1.9530e-01, -2.8484e-01,  ...,  6.1921e-01,
           -5.7693e-02,  1.1141e+00],
          ...,
     

In [62]:
out_torch.backward(torch.ones_like(o2))

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [3]:
import numpy as np
#from tensor import Tensor
#from BatchNorm import BatchNorm
import torch

N,C,H,W = 2,3,4,4

img_t = np.random.randn(N,C,H,W)

In [12]:
from tensor import Tensor
img = Tensor(img_t)

In [76]:
#import numpy as np
#from tensor import Tensor
#from BatchNorm import BatchNorm
#import torch
bn = BatchNorm(num_feats =3)

output = bn(img)


Changed Tensor(data = [1. 1. 1.], grad = 0) Tensor(data = [0. 0. 0.], grad = 0)
mu=Tensor(data = [[[[-0.03333687]]

  [[ 0.23460513]]

  [[ 0.18805282]]]], grad = 0)
var=Tensor(data = [[[[1.15146756]]

  [[1.0252791 ]]

  [[0.81169145]]]], grad = 0)


In [78]:
o2

tensor([[[[-0.9140,  1.5541, -0.4857,  2.6703],
          [-2.2852,  1.3853, -0.3243, -0.2378],
          [-0.2192, -0.7823,  0.6649,  1.4055],
          [-0.9424,  0.1205,  1.0601,  0.1943]],

         [[-2.1895,  1.3304,  0.2900,  1.7394],
          [-1.4406,  1.4581,  0.2652,  1.5393],
          [ 0.8078,  0.7346,  0.0826, -0.7826],
          [ 0.5718, -0.0468, -0.2557, -0.6868]],

         [[-1.3961,  0.9195,  0.5097,  0.0304],
          [ 0.4641,  0.3996, -0.2782, -0.4890],
          [ 0.3179, -2.0279, -0.0979,  1.3985],
          [-0.9711, -0.2634,  0.6741, -0.4993]]],


        [[[ 0.5729,  0.2872,  1.1061,  0.2904],
          [ 1.0168, -0.1672, -0.8937,  0.3250],
          [-1.0344, -0.4336, -0.7510, -1.4438],
          [-0.8650,  0.1839, -0.5817, -0.4762]],

         [[-0.2066,  1.9514, -1.1443, -0.3223],
          [ 0.0250,  0.4032, -0.3078, -0.9256],
          [ 1.2806, -1.2648,  0.1721, -0.7353],
          [ 0.3961, -0.5908, -1.0195, -1.1288]],

         [[ 1.5201,  0.4737,

In [77]:
output

Tensor(data = [[[[-0.91404941  1.55407748 -0.48567905  2.67030519]
   [-2.28516359  1.38529931 -0.32425225 -0.23780134]
   [-0.21917474 -0.78228564  0.66485396  1.40555334]
   [-0.94235994  0.12052279  1.06012196  0.19431807]]

  [[-2.18952801  1.33042274  0.29000338  1.73938283]
   [-1.440597    1.45812202  0.26524198  1.53927624]
   [ 0.80777575  0.73463695  0.08261354 -0.78256547]
   [ 0.57178843 -0.04680691 -0.25566549 -0.68676729]]

  [[-1.39612012  0.91947421  0.50968355  0.03040984]
   [ 0.46413086  0.39958066 -0.27819866 -0.48899825]
   [ 0.31787211 -2.02787866 -0.09788587  1.39852948]
   [-0.97106082 -0.2633817   0.67413989 -0.49925895]]]


 [[[ 0.57287966  0.28719156  1.10611712  0.29036505]
   [ 1.01681912 -0.16720352 -0.89368536  0.3250485 ]
   [-1.03438784 -0.43360959 -0.75098362 -1.44383249]
   [-0.86496118  0.18387678 -0.58171452 -0.47620583]]

  [[-0.20660791  1.95139397 -1.14430445 -0.32228287]
   [ 0.0249993   0.40320232 -0.30779812 -0.92555814]
   [ 1.28056025 -1.264

In [40]:
torch_bn = torch.nn.BatchNorm2d(3, momentum=0.1, affine=False)
out_torch = torch_bn(torch_img)
#torch_bn.weight.data = torch.tensor(bn.gamma.data, dtype=torch.float)
#torch_bn.bias.data = torch.tensor(bn.beta.data,dtype=torch.float)

In [1]:
from tensor import Tensor
import numpy as np

In [ ]:
def create_torch_tensors(*args)

In [ ]:
def create_tests():
    # 1st arg: the function, rest is tensors

    

In [2]:
a = Tensor(np.array([[1,2,3],[4,5,6]]))
b = Tensor(np.array([[1,4,5], [4,3,1]]))

c=a+b

e = Tensor(np.array([1,1,1]))
f = a*e

g = a/f

h = g.sum()

In [3]:
h.backward()

In [6]:
import torch

a_tenser = torch.tensor(a.data, dtype=float, requires_grad= True)
b_tenser = torch.tensor(b.data, dtype=float, requires_grad= True)
e_tenser = torch.tensor(e.data, dtype=float, requires_grad= True)

In [9]:
c_tensor=a_tenser+b_tenser

f_tenser = a_tenser*e_tenser
a_tenser.retain_grad()
f_tenser.retain_grad()
g_tensor = a_tenser/f_tenser
g_tensor.retain_grad()
h_tenser = g_tensor.sum()
h_tenser.backward()

In [13]:
s = b_tenser.relu()
print(s)
o = s.sum()
o.backward()

tensor([[1., 4., 5.],
        [4., 3., 1.]], dtype=torch.float64, grad_fn=<ReluBackward0>)


In [18]:
s2 = b.relu()
o2 = s2.sum()
o2.backward()

In [20]:
b_tenser.grad, b.grad

(tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64),
 array([[1, 1, 1],
        [1, 1, 1]]))

In [8]:
x = Tensor(np.array([[1,2,3],[4,5,6]]))
y = Tensor(np.array([[1,2,3]]))
z = Tensor(np.array([1,1,1]))
a,b,c = x,y,z
d = a+b # Broadcast
d.retain_grad()
e = a-b
e.retain_grad()
f = d*e
f.retain_grad()
g = f/c

In [1]:
import numpy as np
import torch
from tensor import Tensor

In [11]:
    x = Tensor(np.array([[1,2,3],[4,5,6]]))
    y = Tensor(np.array([[1,2,3]]))
    z = Tensor(np.array([1,1,1]))
    a,b,c = x,y,z
    d = a+b # Broadcast
    d.retain_grad()
    e = a-b
    
    e.retain_grad()
    f = d*e
    k = f.mean()
    
    k.backward()

In [12]:
a.grad, b.grad, d.grad, e.grad

(array([[0.33333333, 0.66666667, 1.        ],
        [1.33333333, 1.66666667, 2.        ]]),
 array([-5., -5., -5.]),
 array([[0. , 0. , 0. ],
        [0.5, 0.5, 0.5]]),
 array([[0.33333333, 0.66666667, 1.        ],
        [0.83333333, 1.16666667, 1.5       ]]))

In [14]:
d.grad.sum(axis=0)  - e.grad.sum(axis=0)

array([-0.66666667, -1.33333333, -2.        ])

In [16]:
a.grad, b.grad, d.grad, e.grad

(tensor([[5.6667e+00, 1.2333e+01, 1.7000e+01],
         [4.3587e+06, 2.1980e+09, 1.0641e+12]], dtype=torch.float64),
 tensor([[-1.0897e+06, -8.7921e+08, -5.3205e+11]], dtype=torch.float64),
 tensor([[0.0000, 0.0000, 0.0000],
         [0.5000, 0.5000, 0.5000]], dtype=torch.float64),
 tensor([[0.3333, 0.6667, 1.0000],
         [0.8333, 1.1667, 1.5000]], dtype=torch.float64))

In [15]:
   
    a,b,c = x_t,y_t,z_t
    d = a+b # Broadcast
    d.retain_grad()
    e = a-b
    
    e.retain_grad()
    f = d*e
    k = f.mean()
    
    k.backward()

In [4]:
w = 0
w+= np.array([0.33333333, 0.33333333, 0.33333333])

In [5]:
w

array([0.33333333, 0.33333333, 0.33333333])

In [5]:
np.random.randn(3).shape

(3,)

In [3]:
np.array([0]) + np.random.randn(3)

array([-0.33588985, -1.87211256,  1.63406184])

In [3]:
b.grad

0

In [11]:
e.grad

array([[3.33333333e-01, 6.66666667e-01, 1.00000000e+00],
       [2.72418114e+06, 1.53861836e+09, 7.98072361e+11]])

In [15]:
grads_true1[1]

tensor([[-1.0897e+06, -8.7921e+08, -5.3205e+11]], dtype=torch.float64)

In [14]:
b

Tensor(data = [[1 2 3]], grad = [[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.26901737e+06 1.31881573e+09 5.32048241e+11]])

In [9]:
print(f'{e},\n{f=},\n{g},\n{h=}\n,{i=}')

Tensor(data = [[0 0 0]
 [3 3 3]], grad = 0),
f=Tensor(data = [[ 0  0  0]
 [15 21 27]], grad = 0),
Tensor(data = [[ 0.  0.  0.]
 [15. 21. 27.]], grad = [[1.66666667e-01 1.66666667e-01 1.66666667e-01]
 [5.44836229e+05 2.19802622e+08 8.86747068e+10]]),
h=Tensor(data = [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [3.26901737e+06 1.31881573e+09 5.32048241e+11]], grad = [[0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667]])
,i=Tensor(data = [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [3.26901737e+06 1.31881573e+09 5.32048241e+11]], grad = [[0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667]])


In [14]:
import torch
from tensor import Tensor
import numpy as np

x = Tensor(np.array([[1,2,3],[4,5,6]]))
y = Tensor(np.array([[1,2,3]]))
z = Tensor(np.array([1,1,1]))
x2 = Tensor(np.array([[2,3],[5,6],[7,8]]))

x_t = torch.tensor(x.data, dtype=float, requires_grad=True)
y_t = torch.tensor(y.data, dtype=float, requires_grad=True)
z_t = torch.tensor(z.data, dtype=float, requires_grad=True)
x2_t = torch.tensor(x2.data, dtype=float, requires_grad=True)

def perform_ops(a,b,c):
    d = a+b # Broadcast
    d.retain_grad()
    e = a-b
    e.retain_grad()
    f = d*e
    f.retain_grad()
    g = f/c
    g.retain_grad()
    h = g.exp()
    h.retain_grad()
    i = h.relu()
    i.retain_grad()
    print(i)
    j = i.softmax()
    j.retain_grad()
    k = j.mean()
    
    k.backward()

    return [a.grad, b.grad, c.grad, d.grad, e.grad, f.grad, g.grad, h.grad, i.grad, j.grad, k.grad]

def perform_ops2(a,b):
    c = a@b
    c.retain_grad()
    d = c**3
    d.retain_grad()
    e = d.sum()

    e.backward()
    return [a.grad, b.grad, c.grad, d.grad, e.grad]

grads1 = perform_ops(x,y,z)
grads2 = perform_ops2(x,x2)
grads_true1 = perform_ops(x_t, y_t, z_t)
grads_true2 = perform_ops2(x_t, x2_t)


def test_compare():
    for i,j in zip(grads1, grads_true1):
        try:
           assert np.allclose(i, j.detach().numpy())
        except:
            assert j == None
    for i,j in zip(grads2, grads_true2):
        try:
           assert np.allclose(i, j.detach().numpy())
        except:
            assert j == None


Tensor(data = [[1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [3.26901737e+06 1.31881573e+09 5.32048241e+11]], grad = 0)
tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00],
        [3.2690e+06, 1.3188e+09, 5.3205e+11]], dtype=torch.float64,
       grad_fn=<ReluBackward0>)


TypeError: softmax() received an invalid combination of arguments - got (), but expected one of:
 * (int dim, torch.dtype dtype)
 * (name dim, *, torch.dtype dtype)


In [17]:
b.grad.shape

(2, 3)

In [6]:
y.data.ndim

2

In [7]:
y.shape

(1, 3)

In [10]:
import numpy as np
x = Tensor(np.array([[1,2,3],[4,5,6]]))
s = x.softmax()

In [12]:
s.backward(np.random.randn(x.shape[0], x.shape[1]))

In [1]:
m = x.mean()
m

NameError: name 'x' is not defined

In [3]:
import torch
from tensor import Tensor
import numpy as np
x = Tensor(np.array([[1,2,3],[4,5,6]]))
y = Tensor(np.array([[1,2,3]]))
z = Tensor(np.array([1,1,1]))
x2 = Tensor(np.array([[2,3],[5,6],[7,8]]))

def perform_ops(a,b,c):
    d = a+b # Broadcast
    d.retain_grad()
    e = a-b
    e.retain_grad()
    f = d*e
    f.retain_grad()
    g = f/c
    g.retain_grad()
    h = g.exp()
    h.retain_grad()
    i = h.relu()
    i.retain_grad()
    #j = i.softmax()
    #j.retain_grad()
    k = i.mean()
    
    k.backward()

    return [a.grad, b.grad, c.grad, d.grad, e.grad, f.grad, g.grad, h.grad, i.grad, k.grad]

def perform_ops2(a,b):
    c = a@b
    c.retain_grad()
    d = c.sum()

    d.backward()
    return [a.grad, b.grad, c.grad, d.grad]


def compare(grads, torch_grads):
    for i,j in zip(grads, torch_grads):
        try:
           assert np.allclose(i, j.detach().numpy())
        except:
            assert j == None

In [2]:
x_t = torch.tensor(x.data, dtype=float, requires_grad=True)
y_t = torch.tensor(y.data, dtype=float, requires_grad=True)
z_t = torch.tensor(z.data, dtype=float, requires_grad=True)
x2_t = torch.tensor(x2.data, dtype=float, requires_grad=True)

In [5]:
compare(grads1, grads_true1)

In [19]:
compare(grads2, grads_true2)

In [13]:
grads1[-1]

array([1])

In [4]:
grads1 = perform_ops(x,y,z)
grads2 = perform_ops2(x,x2)
grads_true1 = perform_ops(x_t, y_t, z_t)
grads_true2 = perform_ops2(x_t, x2_t)

C:\Users\Camel\AppData\Local\Temp\ipykernel_14652\4122796782.py:28: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  return [a.grad, b.grad, c.grad, d.grad, e.grad, f.grad, g.grad, h.grad, i.grad, k.grad]
C:\Users\Camel\AppData\Local\Temp\ipykernel_14652\4122796782.py:36: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you

In [10]:
e.grad.sum(axis=0)

array([2.72418148e+06, 1.53861836e+09, 7.98072361e+11])

In [12]:
-2.72418148e+06+1.63450869e+06

-1089672.79

In [8]:
d.grad

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.63450869e+06, 6.59407867e+08, 2.66024120e+11]])

In [4]:
grads1

[array([[5.33333333e+00, 1.16666667e+01, 1.60000000e+01],
        [4.35869483e+06, 2.19802624e+09, 1.06409648e+12]]),
 array([[-1.08967279e+06, -8.79210490e+08, -5.32048241e+11]]),
 array([-8.17254343e+06, -4.61585507e+09, -2.39421708e+12]),
 array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [1.63450869e+06, 6.59407867e+08, 2.66024120e+11]]),
 array([[3.33333333e-01, 6.66666667e-01, 1.00000000e+00],
        [2.72418114e+06, 1.53861836e+09, 7.98072361e+11]]),
 array([[1.66666667e-01, 1.66666667e-01, 1.66666667e-01],
        [5.44836229e+05, 2.19802622e+08, 8.86747068e+10]]),
 array([[1.66666667e-01, 1.66666667e-01, 1.66666667e-01],
        [5.44836229e+05, 2.19802622e+08, 8.86747068e+10]]),
 array([[0.16666667, 0.16666667, 0.16666667],
        [0.16666667, 0.16666667, 0.16666667]]),
 array([[0.16666667, 0.16666667, 0.16666667],
        [0.16666667, 0.16666667, 0.16666667]]),
 array([1])]

In [7]:
grads_true1

[tensor([[5.3333e+00, 1.1667e+01, 1.6000e+01],
         [4.3587e+06, 2.1980e+09, 1.0641e+12]], dtype=torch.float64),
 tensor([[-1.0897e+06, -8.7921e+08, -5.3205e+11]], dtype=torch.float64),
 tensor([-8.1725e+06, -4.6159e+09, -2.3942e+12], dtype=torch.float64),
 tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.6345e+06, 6.5941e+08, 2.6602e+11]], dtype=torch.float64),
 tensor([[3.3333e-01, 6.6667e-01, 1.0000e+00],
         [2.7242e+06, 1.5386e+09, 7.9807e+11]], dtype=torch.float64),
 tensor([[1.6667e-01, 1.6667e-01, 1.6667e-01],
         [5.4484e+05, 2.1980e+08, 8.8675e+10]], dtype=torch.float64),
 tensor([[1.6667e-01, 1.6667e-01, 1.6667e-01],
         [5.4484e+05, 2.1980e+08, 8.8675e+10]], dtype=torch.float64),
 tensor([[0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667]], dtype=torch.float64),
 tensor([[0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667]], dtype=torch.float64),
 None]

In [5]:
grads2

[array([[5.33333333e+00, 1.16666667e+01, 1.60000000e+01],
        [4.35869483e+06, 2.19802624e+09, 1.06409648e+12]]),
 array([[5, 5],
        [7, 7],
        [9, 9]]),
 array([[1, 1],
        [1, 1]]),
 array([1])]

In [17]:
e.grad

array([[3.33333333e-01, 6.66666667e-01, 1.00000000e+00],
       [2.72418114e+06, 1.53861836e+09, 7.98072361e+11]])

In [11]:
f.grad

array([[1.66666667e-01, 1.66666667e-01, 1.66666667e-01],
       [5.44836229e+05, 2.19802622e+08, 8.86747068e+10]])

In [26]:
grads_true1

[tensor([[5.3333e+00, 1.1667e+01, 1.6000e+01],
         [4.3587e+06, 2.1980e+09, 1.0641e+12]], dtype=torch.float64),
 tensor([[-1.0897e+06, -8.7921e+08, -5.3205e+11]], dtype=torch.float64),
 tensor([-8.1725e+06, -4.6159e+09, -2.3942e+12], dtype=torch.float64),
 tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.6345e+06, 6.5941e+08, 2.6602e+11]], dtype=torch.float64),
 tensor([[3.3333e-01, 6.6667e-01, 1.0000e+00],
         [2.7242e+06, 1.5386e+09, 7.9807e+11]], dtype=torch.float64),
 tensor([[1.6667e-01, 1.6667e-01, 1.6667e-01],
         [5.4484e+05, 2.1980e+08, 8.8675e+10]], dtype=torch.float64),
 tensor([[1.6667e-01, 1.6667e-01, 1.6667e-01],
         [5.4484e+05, 2.1980e+08, 8.8675e+10]], dtype=torch.float64),
 tensor([[0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667]], dtype=torch.float64),
 tensor([[0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667]], dtype=torch.float64),
 None]

In [14]:
o

tensor(18., dtype=torch.float64, grad_fn=<SumBackward0>)

In [11]:
a_tenser.grad

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [5]:
f

Tensor(data = [[1 2 3]
 [4 5 6]], grad = [[-1.         -0.5        -0.33333333]
 [-0.25       -0.2        -0.16666667]])

In [10]:
h_tenser.grad

C:\Users\Camel\AppData\Local\Temp\ipykernel_7568\2686631694.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  h_tenser.grad


In [4]:
f.grad

array([[-1.        , -0.25      , -0.11111111],
       [-0.0625    , -0.04      , -0.02777778]])

In [9]:
f_tenser.grad

tensor([[-1.0000, -0.5000, -0.3333],
        [-0.2500, -0.2000, -0.1667]], dtype=torch.float64)

In [8]:
g_tensor.grad, g.grad

(tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [16]:
a.grad, a_tenser.grad

(array([[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]], dtype=torch.float64))

In [ ]:
import torch



In [3]:
d = c.mean()
d.backward()
print(a.grad, b.grad)

AddBack
[[0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667]] [[0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667]]
[[0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667]] [[0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667]]


In [5]:
a.grad

array([[2.32514881e-05, 2.32514881e-05, 2.32514881e-05],
       [2.32514881e-05, 2.32514881e-05, 2.32514881e-05]])

In [5]:
b.grad

array([[0.02564103, 0.02564103, 0.02564103],
       [0.02564103, 0.02564103, 0.02564103]])

In [4]:
import torch
a_tensor = torch.tensor(a.data,dtype=float, requires_grad=True)
b_tensor = torch.tensor(b.data,dtype=float, requires_grad=True)
c_tensor = a_tensor+b_tensor

In [5]:
d_tensor=  c_tensor.mean()
d_tensor.backward()

In [20]:
d_tensor

tensor(6.5000, dtype=torch.float64, grad_fn=<MeanBackward0>)

In [21]:
d

Tensor(data = 6.5, grad = [1])

In [6]:
a_tensor.grad, b_tensor.grad

(tensor([[0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667]], dtype=torch.float64),
 tensor([[0.1667, 0.1667, 0.1667],
         [0.1667, 0.1667, 0.1667]], dtype=torch.float64))

In [17]:
output.shape, out_torch.shape

((2, 3, 4, 4), torch.Size([2, 3, 4, 4]))

In [27]:
import torch
torch_img = torch.tensor(img_t, dtype=torch.float)
torch_bn = torch.nn.BatchNorm2d(3)
out_torch = torch_bn(torch_img)

In [28]:
out_torch

tensor([[[[-0.9140,  1.5541, -0.4857,  2.6703],
          [-2.2852,  1.3853, -0.3243, -0.2378],
          [-0.2192, -0.7823,  0.6649,  1.4055],
          [-0.9424,  0.1205,  1.0601,  0.1943]],

         [[-2.1895,  1.3304,  0.2900,  1.7394],
          [-1.4406,  1.4581,  0.2652,  1.5393],
          [ 0.8078,  0.7346,  0.0826, -0.7826],
          [ 0.5718, -0.0468, -0.2557, -0.6868]],

         [[-1.3961,  0.9195,  0.5097,  0.0304],
          [ 0.4641,  0.3996, -0.2782, -0.4890],
          [ 0.3179, -2.0279, -0.0979,  1.3985],
          [-0.9711, -0.2634,  0.6741, -0.4993]]],


        [[[ 0.5729,  0.2872,  1.1061,  0.2904],
          [ 1.0168, -0.1672, -0.8937,  0.3250],
          [-1.0344, -0.4336, -0.7510, -1.4438],
          [-0.8650,  0.1839, -0.5817, -0.4762]],

         [[-0.2066,  1.9514, -1.1443, -0.3223],
          [ 0.0250,  0.4032, -0.3078, -0.9256],
          [ 1.2806, -1.2648,  0.1721, -0.7353],
          [ 0.3961, -0.5908, -1.0195, -1.1288]],

         [[ 1.5201,  0.4737,